# Generated by Django 5.1.3 on 2024-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='vector.jpg', upload_to='agents'),
        ),
    ]
